###

POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{  "email": "michele2@test.com", "password": "michele", "is_staff":"True"  }


###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjE5NzYyLCJpYXQiOjE3MzQ2MTk0NjIsImp0aSI6IjQ2ZGY2MzRkZTVmNDQyMjM5ZmE2YmRmYTNmYjZhZDNkIiwidXNlcl9pZCI6MywiZW1haWwiOiJtaWNoZWxlQHRlc3QuY29tIn0.C_e_FWB3Uoj1WKfEpExkeePw64xW48zWEz_GtXDdDCE

{  "email": "test@test.com", "password": "michele" }



###

GET http://127.0.0.1:8000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIyOTAxLCJpYXQiOjE3NDAzMjIzMDEsImp0aSI6IjM2YTg5OGI2NWYyZDRkYTJiNWU3ZmZlNWJkNGU0YjE2IiwidXNlcl9pZCI6MSwibmFtZSI6InRlc3QifQ.VRzlkKA2kVFTrE8Xjlh4TrO89MYxC0ZwQ2TRDHTaunw

###

POST http://127.0.0.1:8000/api/delete/
Content-Type: application/json

{  "id":"2" }


###

GET http://127.0.0.1:8000/api/test_auth_token
Content-Type: application/json
Authorization: token 5490264ffb3dc1f802240c78688288be319d6551


###

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{  "email": "test@test.com", "password": "admin"}



###

POST http://127.0.0.1:8000/api/token/refresh
Content-Type: application/json

{ 
 "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNDQ1MzE1NiwiaWF0IjoxNzM0MzY2NzU2LCJqdGkiOiIyYzNjYjU1MmRlMTc0MGVlYjQ0MGYyMDczYzgwYmM0NSIsInVzZXJfaWQiOjF9.UYFb8lqghiYr_C6qISoqgkjqmd6wdG14LABPDFl5dLE"

}


###
GET http://127.0.0.1:8000/api/config
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIyOTAxLCJpYXQiOjE3NDAzMjIzMDEsImp0aSI6IjM2YTg5OGI2NWYyZDRkYTJiNWU3ZmZlNWJkNGU0YjE2IiwidXNlcl9pZCI6MSwibmFtZSI6InRlc3QifQ.VRzlkKA2kVFTrE8Xjlh4TrO89MYxC0ZwQ2TRDHTaunw

###
GET http://127.0.0.1:8000/api/version
Content-Type: application/json
