###

POST http://127.0.0.1:8001/api/signup/
Content-Type: application/json

{  "email": "giovanni@test.com", "password": "admin1234", "is_superuser":"True", "is_staff":"True" }


###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{  "email": "normaluser@test.com", "password": "user" }



###

GET http://127.0.0.1:8000/api/users
Content-Type: application/json
Authorization: token e93a510a04862955279b8ac1a214ef1cee4aeebd



###

POST http://127.0.0.1:8000/api/delete/
Content-Type: application/json

{  "id":"2" }


###

GET http://127.0.0.1:8001/api/test_auth_token
Content-Type: application/json
Authorization: token e6e1b12dbcdad1c147ef8af63ed80410cc11fca4


###

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{ "email": "test@test.com", "password": "admin" }



###

POST http://127.0.0.1:8000/api/token/refresh
Content-Type: application/json

{ 
 "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNDQ1MzE1NiwiaWF0IjoxNzM0MzY2NzU2LCJqdGkiOiIyYzNjYjU1MmRlMTc0MGVlYjQ0MGYyMDczYzgwYmM0NSIsInVzZXJfaWQiOjF9.UYFb8lqghiYr_C6qISoqgkjqmd6wdG14LABPDFl5dLE"

}