FROM python:3.11.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

ARG REQUIREMENTS_FILE

COPY ./$REQUIREMENTS_FILE ./

RUN pip install --upgrade pip
RUN pip install -r $REQUIREMENTS_FILE --no-cache-dir

COPY . /app

EXPOSE 8000