### ADD

POST http://127.0.0.1:8000/fhir/create/
Content-Type: application/json

{  "name": "hapi-server2", "host": "127.0.0.1", "port":"8001", "description":"just a new test" }



### DELETE

DELETE http://127.0.0.1:8000/fhir/delete/2
Content-Type: application/json


### LIST
GET http://127.0.0.1:8000/fhir/servers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NTMwMzgwLCJpYXQiOjE3MzQ1MzAwODAsImp0aSI6ImJiN2YwODRmNzU5OTQwOGZhNGVhYTZkODNiNDg4ZDkwIiwidXNlcl9pZCI6MX0.OhIl784ybMfvC9AItaLDbt8yeJ9JaglwKSQnlqNrNic